# Configuración del plugin LastLocation

# Lista de mundos en los que el plugin no hará teletransporte ni guardará ubicaciones.
worlds-blacklist:
  - world_nether     # Mundo del Nether
  - world_the_end    # Mundo del End
  # Añadir más mundos según sea necesario, por ejemplo:
  # - mundo_de_prueba

# Mensajes personalizables
messages:
  teleportacion: "¡Te hemos teletransportado a tu última ubicación!"  # Mensaje al teletransportar a un jugador
  no_last_location: "No se ha guardado ninguna ubicación para ti en este mundo."  # Mensaje si no hay ubicación guardada
  world_blacklisted: "Este mundo está en la lista negra, no se puede teletransportar."  # Mensaje si el mundo está en lista negra

# Otras configuraciones personalizables
other-settings:
  enable-feature-x: true   # Cambiar a false para desactivar alguna característica
